Benchmarks and performance fix
ACEsuit/Polynomials4ML.jl pull request #67
Opened 2023-09-22 18:35 UTC by CheukHinHoJerry

Updates from this branch (To be updated)

- add freeze parameter ProductBasis
- type stability fix
- commented out `FlexArray` interface
- bounds check in `SparseSymProd` and 

cc @DexuanZhou 

@cortner : will let you know once it is ready.

2023-09-23 08:06 UTC, CheukHinHoJerry commented
I think at the end of the PR we should try to generate ALL profview so that we can make sure the time cost go to the right place.

2023-10-05 21:11 UTC, cortner requested changes

2023-10-05 21:11 UTC, cortner commented on src/lux.jl
> +   release!(X)
flag in LuxLayer on whether or not inputs can be released.

2023-10-08 18:39 UTC, cortner commented
@CheukHinHoJerry  -- the only change since we discussed it is the flag for whether or not to release?

2023-10-08 18:41 UTC, CheukHinHoJerry commented
> @CheukHinHoJerry -- the only change since we discussed it is the flag for whether or not to release? I.e. I should just go ahead and merge this?

Yes - I think this is the only thing. And we talked about moving `AtomicorbitalRadius` and wf related stuffs out of this package but I think it should not be done in this PR anyways.

2023-10-08 20:57 UTC, merged